### ISSUE TITLE
error

### ISSUE THREAD

**Issue by S4mmis** [NanMetal/WorldQuestTab#10]
bad argument #1 to '?' (Usage: local info = C_QuestLog.GetQuestTagInfo(questID))
[string "=[C]"]: ?
[string "@WQAchievements/WQAchievements.lua"]:1011: in function `Reward'
[string "@WQAchievements/WQAchievements.lua"]:285: in function `CreateQuestList'
[string "@WQAchievements/WQAchievements.lua"]:529: in function `?'
[string "@ElvUI_Libraries/Core/Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...UI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local info = C_QuestLog.GetQuestTagInfo(questID))"

**Comment by devwrk** [comment]
This error is for the addon [WQAchievements](https://github.com/Urtgard/WQAchievements) and not WorldQuestTab

**Comment by S4mmis** [comment]
M
