### ISSUE TITLE
[Feature request] Reward quantity text label

### ISSUE THREAD

**Issue by Slackluster** [NanMetal/WorldQuestTab#11]
The icons on the world map can optionally have a time left label.
It'd be great if we had an option to show the reward's quantity or item level there, instead.
For currency rewards it'd show the amount (gold, pet charms), for rep rewards the rep, for gear the item level, etc.

**Comment by NanMetal** [comment]
Sorry for the delay. Just updated it. Based on this I made a new option to change that little label with the time left or the reward info :). A little dirty but should work

**Comment by Slackluster** [comment]
This seems to be working perfectly so far, and I fully support this method of implementing it in the settings (it makes a lot of sense and should be clear for users also).

Thank you so much! ❤️
