### ISSUE TITLE
Vol'dun's map messy

### ISSUE THREAD

**Issue by pepedressingroom** [NanMetal/WorldQuestTab#12]
I'm not sure when did this issue come out again.
These messy quests are of Dragonflight expansion. 
![WoWScrnShot_111524_192358](https://github.com/user-attachments/assets/affc6602-2d80-4c2e-a08f-c320cc72d051)

There was a fix by Tga123 https://github.com/Tga123/WorldQuestTab/commit/e9233aa29c0fb5377f37fa981b86baf5f32fd3a6
Tga123 mentioned "MapUtil.ShouldShowTask" which you ever mentioned.

Regards

**Comment by NanMetal** [comment]
Super strange, the fix is already there on the code. I will check what's wrong

**Comment by NanMetal** [comment]
I found the problem, it was me. Should be fixed now
