### ISSUE TITLE
Dragon icon small

### ISSUE THREAD

**Issue by reyard** [NanMetal/WorldQuestTab#14]
The dragon icon for great rewards like a world boss is soo small, I think it should be big

I change in MapPinProvider.xml

line 15 `<Anchor point="TOPLEFT" x="-10" y="11"/>`
line 16 `<Anchor point="BOTTOMRIGHT" x="11" y="-11"/>`

it was

line 15 `<Anchor point="TOPLEFT" x="-6" y="7"/>`
line 16 `<Anchor point="BOTTOMRIGHT" x="7" y="-7"/>`

**Comment by NanMetal** [comment]
Yes, it is intentional. I made it small like the original. I don't want the pin to be twice as big, they are big enough.
