### ISSUE TITLE
[Question] How to grab WQT's world quest pin frames and questID

### ISSUE THREAD

**Issue by Slackluster** [NanMetal/WorldQuestTab#15]
Hello!

I'm working on integrating WQT into my addon, by adding an icon on the quest rewards where appropriate.

Now I've managed to do this for the quest list WQT provides (rather poorly, I assume, but functional! :D), but I cannot find a way to grab the frames for the pins on the world map. Is there a way to grab those frames and their related questIDs?

**Comment by Fluke667** [comment]
Your addon is?

**Comment by Slackluster** [comment]
https://github.com/Sluimerstand/TransmogLootHelper
(The new feature isn't described yet on there.)

**Comment by NanMetal** [comment]
Hello! Not really sure, the active pin frames are inside WQT_PinDataProvider.pinPools, most likely you cannot access it https://github.com/NanMetal/WorldQuestTab/blob/cbba00724657143046badc77e96f4314a90159ce/MapPinProvider.lua#L114

You can try get all the children inside the worldmap and check if the frame template is "WQT_PinTemplate" or "BUTTON" and filter from there.
See inside the world map frame:
`WorldMapFrame.ScrollContainer.Child:GetChildren()`

Once you get the pin you can get the quest id there, also look inside questInfo table

**Comment by Slackluster** [comment]
First of all, thank you for taking the time to respond to my questions!

While you can use `WorldMapFrame:EnumeratePinsByTemplate` or your method to iterate through all the map pins, the WQT frames actually don't have any PinTemplate element to them (at least not readable by other addons).

I managed to identify the WQT pins by iterating through the world map pins and looking for the `RingBG` frame, which is always and only present on WQT frames as far as I can see.

Thank you again for indulging my curiosity. :)
