### ISSUE TITLE
The Magical Wreath of Bonus Objectives

### ISSUE THREAD

**Issue by Slackluster** [NanMetal/WorldQuestTab#16]
![image](https://github.com/user-attachments/assets/ac55d7b3-d743-4b47-a801-82a060ac6dc1)

So there's this spot on Vol'dun where the game seems to store bonus objectives for killing rares; I think I've recognised rares from BFA and DF among these. They're normally hidden, but WQT seems to pick up on this. :D

**Comment by NanMetal** [comment]
Yess this was fixed in the last version! Now I see that I didn't create a new release, my bad
