### ISSUE TITLE
World Quest not displayed on Siren Isle

### ISSUE THREAD

**Issue by pepedressingroom** [NanMetal/WorldQuestTab#19]
When in Siren Isle, the world quest "[Legacy of the Vrykul](https://www.wowhead.com/quest=84852)" cannot be properly displayed neither on map nor WQT list.
While the “[Special Assignment: Storm's a Brewin](https://www.wowhead.com/quest=85113)” can be properly displayed both on map and WQT list when in Siren Isle.

BUT when NOT in Siren Isle, the world quest "[Legacy of the Vrykul](https://www.wowhead.com/quest=84852)" displays while you shift to Siren Isle map.

**Comment by NanMetal** [comment]
I think I got it working now
