### ISSUE TITLE
Display when a world quest awards a one-time reputation bonus

### ISSUE THREAD

**Issue by Ezupio** [NanMetal/WorldQuestTab#2]
First off, I really want to thank you so much for having updated the add-on, it's been a staple for me for a while now and it really warms my heart to see it updated for TWW, since it had already been forked by a couple different people for SL and DF, I got a bit scared no one would keep the torch lit.
So yeah, thanks a bunch !

Now if I could make a small request, world quests now display a new message "World quest will award a one-time warband reputation bonus" when hovered. It would be terrific if this could be added to the add-on. Just adding the text would be fine as far as I'm concerned, but perhaps a small icon could be added in the tab and/or on the world quest circle to indicate this piece of information at a glance as well.

Cheers,
Yann

**Comment by NanMetal** [comment]
Just got to 80, I am a little confused with the new world quests in TWW at the moment. I see what you mean, it shows only in the tooltip with the addon disabled. I will see what can I do

**Comment by NanMetal** [comment]
Took me alot of time to figure this out (WoW APIs and stuff)...
Hope this suits well, still not sure about the looks of the warband bonuses on the map pins and quest list, at the moment I will leave it as is (the little red icon).
If everything related to this is good, we can close this.

**Comment by Ezupio** [comment]
Just checked it out, seems perfect to me !

The red warband icon is ideal imo, it's Blizzard's own iconography for warbands after all, and it's great to see at a glance which world quest you might want to do no matter the actual "main" reward.

With the rep changes from TWW, if you're going to play several characters I feel like it's really important to be able to see which wq you've already done on a different character to know if you should prioritize it or not.

Thank you so much !
