### ISSUE TITLE
Flight Map Issue

### ISSUE THREAD

**Issue by cybern4ut** [NanMetal/WorldQuestTab#3]
When opening the flight map and pressing the World Quest Tab icon. TWW definitely broke this.
It would be nice if you could look into it! Thank you.

![image](https://ptpimg.me/iom3y3.jpg)

**Comment by NanMetal** [comment]
Alright this happens to me too. I will have a look at this next.

**Comment by NanMetal** [comment]
Heyy!! I think is working good now, you can test the latest version :)
Please test it, if this is fixed on your end too we can close this.

**Comment by cybern4ut** [comment]
Everything looks great now, we can close this. Flawless man :)

**Comment by cybern4ut** [comment]
Everything looks great now, we can close this.
