### ISSUE TITLE
How fix this?

### ISSUE THREAD

**Issue by reyard** [NanMetal/WorldQuestTab#4]
How can I fix this?

1x WorldQuestTab/Data.lua:1050: attempt to call global 'GetAddOnEnableState' (a nil value)
[string "@WorldQuestTab/Data.lua"]:1050: in function <WorldQuestTab/Data.lua:1050>
[string "=(tail call)"]: ?
[string "@WorldQuestTab/Settings.lua"]:87: in function `UpdateState'
[string "@WorldQuestTab/Settings.lua"]:214: in function `UpdateState'
[string "@WorldQuestTab/Settings.lua"]:205: in function `Init'
[string "@WorldQuestTab/Settings.lua"]:893: in function `AddSetting'
[string "@WorldQuestTab/Settings.lua"]:912: in function `AddSettingList'
[string "@WorldQuestTab/Settings.lua"]:745: in function `Init'
[string "@WorldQuestTab/WorldQuestTab.lua"]:948: in function <WorldQuestTab/WorldQuestTab.lua:885>
[string "=[C]"]: ?
[string "@AutoLooter/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <AutoLooter/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AutoLooter/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:96: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:89: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:84: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:76: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:72>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:82: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "WorldQuestTabUtilities"
(*temporary) = "attempt to call global 'GetAddOnEnableState' (a nil value)"

**Comment by NanMetal** [comment]
Mine is working fine in a clean environment. I see WorldQuestTabUtilities there, are you using it? If so, that's the problem. It is not compatible with this fork.

**Comment by Fluke667** [comment]
> Mine is working fine in a clean environment. I see WorldQuestTabUtilities there, are you using it? If so, that's the problem. It is not compatible with this fork.

i had using it but the settings there not apply with your version

**Comment by NanMetal** [comment]
I see that that AddOn is still referenced in this fork. I will update it so it does not interfere anymore. I don't plan to integrate it neither. Probably in a future I will consider it

**Comment by Fluke667** [comment]
YEAAAAH Thanks so much

**Comment by NanMetal** [comment]
Alrigh I'm closing this, forgot to reference it to this issue. Should not interfere anymore (I commented everything in the code just in case).
