### ISSUE TITLE
Quest List Icon (suggestion)

### ISSUE THREAD

**Issue by cybern4ut** [NanMetal/WorldQuestTab#7]
Hey hey! it's more of a suggestion cause there is no real issues. I was just going through my options on the Quest list and I was wondering if there could be a way to increase the icon size with the currency or some kind of scaling to it.

![image](https://ptpimg.me/74okxo.jpg)

**Comment by NanMetal** [comment]
Hey!! Sorry not for the moment, maybe in a future
