### ISSUE TITLE
2 new errors on new patch 11.0.5

### ISSUE THREAD

**Issue by reyard** [NanMetal/WorldQuestTab#8]
Today in patch 8.0.5 get 2 new errors on login.

**First was**

14x WorldQuestTab/Dataprovider.lua:747: attempt to compare number with nil
[string "@WorldQuestTab/Dataprovider.lua"]:747: in function `AddQuest'
[string "@WorldQuestTab/Dataprovider.lua"]:716: in function `AddQuestsInZone'
[string "@WorldQuestTab/Dataprovider.lua"]:582: in function `OnUpdate'
[string "@WorldQuestTab/Dataprovider.lua"]:526: in function <WorldQuestTab/Dataprovider.lua:526>

Locals:
self = <table> {
 iterativeList = <table> {
 }
 waitingRoomRewards = <table> {
 }
 pool = <table> {
 }
 callbacks = <table> {
 }
 isUpdating = true
 keyList = <table> {
 }
 updateCD = 0.013000
 numZonesProcessed = 0
 latestZoneId = 2248
 bufferedZones = <table> {
 }
 frame = Frame {
 }
}
qInfo = <table> {
 mapID = 2248
 isCombatAllyQuest = false
 questID = 81710
 childDepth = 0
 isMapIndicatorQuest = false
 y = 0.481521
 x = 0.774354
 numObjectives = 0
 isQuestStart = false
 isMeta = false
 inProgress = false
 isDaily = false
}
duplicate = nil
questInfo = <table> {
 mapInfo = <table> {
 }
 hasRewardData = false
 isValid = false
 reward = <table> {
 }
 rewardList = <table> {
 }
 typeBits = 0
 time = <table> {
 }
}
alwaysHide = true
(*temporary) = nil
(*temporary) = <table> {
 mapID = 2248
 isCombatAllyQuest = false
 questID = 81710
 childDepth = 0
 isMapIndicatorQuest = false
 y = 0.481521
 x = 0.774354
 numObjectives = 0
 isQuestStart = false
 isMeta = false
 inProgress = false
 isDaily = false
}
(*temporary) = false
(*temporary) = 81710
(*temporary) = false
(*temporary) = true
(*temporary) = <table> {
 value = 1
}
(*temporary) = <table> {
 value = 1
}
(*temporary) = "attempt to compare number with nil"
WQT = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 filterOrders = <table> {
 }
 name = "WorldQuestTab"
 orderedModules = <table> {
 }
 isEnabled = true
 baseName = "WorldQuestTab"
 mapWQProvider = <table> {
 }
 defaultModuleState = true
 loadableExternals = <table> {
 }
 settings = <table> {
 }
 db = <table> {
 }
 enabledState = true
}
WQT_Utils = <table> {
}

**And 2nd**

1372x WorldQuestTab/Dataprovider.lua:735: bad argument #1 to 'GetQuestZoneID' (Usage: local uiMapID = C_TaskQuest.GetQuestZoneID(questID))
[string "=[C]"]: in function `GetQuestZoneID'
[string "@WorldQuestTab/Dataprovider.lua"]:735: in function `AddQuest'
[string "@WorldQuestTab/Dataprovider.lua"]:716: in function `AddQuestsInZone'
[string "@WorldQuestTab/Dataprovider.lua"]:582: in function `OnUpdate'
[string "@WorldQuestTab/Dataprovider.lua"]:526: in function <WorldQuestTab/Dataprovider.lua:526>

Locals:
(*temporary) = nil

**Comment by Fluke667** [comment]
16625x WorldQuestTab/Dataprovider.lua:725: bad argument #1 to 'GetQuestZoneID' (Usage: local uiMapID = C_TaskQuest.GetQuestZoneID(questID))
[string "=[C]"]: in function `GetQuestZoneID'
[string "@WorldQuestTab/Dataprovider.lua"]:725: in function `AddQuest'
[string "@WorldQuestTab/Dataprovider.lua"]:706: in function `AddQuestsInZone'
[string "@WorldQuestTab/Dataprovider.lua"]:572: in function `OnUpdate'
[string "@WorldQuestTab/Dataprovider.lua"]:516: in function <WorldQuestTab/Dataprovider.lua:516>

Locals:
(*temporary) = nil

**Comment by HalianElf** [comment]
> 16625x WorldQuestTab/Dataprovider.lua:725: bad argument #1 to 'GetQuestZoneID' (Usage: local uiMapID = C_TaskQuest.GetQuestZoneID(questID)) [string "=[C]"]: in function `GetQuestZoneID' [string "@WorldQuestTab/Dataprovider.lua"]:725: in function `AddQuest' [string "@WorldQuestTab/Dataprovider.lua"]:706: in function `AddQuestsInZone' [string "@WorldQuestTab/Dataprovider.lua"]:572: in function `OnUpdate' [string "@WorldQuestTab/Dataprovider.lua"]:516: in function <WorldQuestTab/Dataprovider.lua:516>
> 
> Locals: (*temporary) = nil

That's with the fixes that were merged? I ran it all last night with no errors after I did the find/replace to update it to the new name.

**Comment by AlexL1118** [comment]
> > 16625x WorldQuestTab/Dataprovider.lua:725: bad argument #1 to 'GetQuestZoneID' (Usage: local uiMapID = C_TaskQuest.GetQuestZoneID(questID)) [string "=[C]"]: in function `GetQuestZoneID' [string "@WorldQuestTab/Dataprovider.lua"]:725: in function `AddQuest' [string "@WorldQuestTab/Dataprovider.lua"]:706: in function `AddQuestsInZone' [string "@WorldQuestTab/Dataprovider.lua"]:572: in function `OnUpdate' [string "@WorldQuestTab/Dataprovider.lua"]:516: in function <WorldQuestTab/Dataprovider.lua:516>
> > Locals: (*temporary) = nil
> 
> That's with the fixes that were merged? I ran it all last night with no errors after I did the find/replace to update it to the new name.

It looks like the OP took the fixes: we see "questID" in the screenshot.
What will happen if a player took the fixes but did not reload UI? Shall we see the old errors and the new code in the error window?

**Comment by HalianElf** [comment]
That's what it showed in the bug sack error prior to the rename. The actual code there was `qInfo.questId` (I still have the errors in my bug sack, I never cleared it)

**Comment by NanMetal** [comment]
I rechecked everything just in case. It's working fine with the last merge.


> > > 16625x WorldQuestTab/Dataprovider.lua:725: bad argument #1 to 'GetQuestZoneID' (Usage: local uiMapID = C_TaskQuest.GetQuestZoneID(questID)) [string "=[C]"]: in function `GetQuestZoneID' [string "@WorldQuestTab/Dataprovider.lua"]:725: in function `AddQuest' [string "@WorldQuestTab/Dataprovider.lua"]:706: in function `AddQuestsInZone' [string "@WorldQuestTab/Dataprovider.lua"]:572: in function `OnUpdate' [string "@WorldQuestTab/Dataprovider.lua"]:516: in function <WorldQuestTab/Dataprovider.lua:516>
> > > Locals: (*temporary) = nil
> > 
> > 
> > That's with the fixes that were merged? I ran it all last night with no errors after I did the find/replace to update it to the new name.
> 
> It looks like the OP took the fixes: we see "questID" in the screenshot. What will happen if a player took the fixes but did not reload UI? Shall we see the old errors and the new code in the error window?

No, it is telling you the usage of the function. You need to /reload for the changes to take effect. If not, old code is still loaded on memory and running (errors will point to the old code if you did in fact not reload)

**Comment by reyard** [comment]
Well now says this error

4x WorldQuestTab/WorldQuestTab.lua:431: attempt to index local 'b' (a nil value)
[string "@WorldQuestTab/WorldQuestTab.lua"]:431: in function <WorldQuestTab/WorldQuestTab.lua:429>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@WorldQuestTab/WorldQuestTab.lua"]:1449: in function `ApplySort'
[string "@WorldQuestTab/WorldQuestTab.lua"]:1512: in function `UpdateQuestList'
[string "@WorldQuestTab/WorldQuestTab.lua"]:1933: in function `func'
[string "@WorldQuestTab/Data.lua"]:47: in function `TriggerCallback'
[string "@WorldQuestTab/Dataprovider.lua"]:620: in function `UpdateWaitingRoom'
[string "@WorldQuestTab/Dataprovider.lua"]:555: in function `OnEvent'
[string "@WorldQuestTab/Dataprovider.lua"]:527: in function <WorldQuestTab/Dataprovider.lua:527>

Locals:
a = <table> {
 mapInfo = <table> {
 }
 hasRewardData = true
 alwaysHide = false
 isValid = true
 questID = 57157
 reward = <table> {
 }
 isAllyQuest = false
 rewardList = <table> {
 }
 passedFilter = true
 isDaily = false
 tagInfo = <table> {
 }
 typeBits = 10
 time = <table> {
 }
 hasWarbandBonus = false
}
b = nil
sortID = 3
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'b' (a nil value)"
_V = <table> {
 WQT_ZONE_EXPANSIONS = <table> {
 }
 WQT_COLOR_ARTIFACT = <table> {
 }
 PATCH_NOTES = <table> {
 }
 WQT_PURPLE_FONT_COLOR = <table> {
 }
 DEBUG_OUTPUT_TYPE = <table> {
 }
 CURRENT_EXPANSION = 10
 PIN_VISIBILITY_CONTINENT = <table> {
 }
 NUMBER_ABBREVIATIONS = <table> {
 }
 REWARD_TYPE_ATLAS = <table> {
 }
 PIN_VISIBILITY_ZONE = <table> {
 }
 LATEST_UPDATE = "<html><body><h3>&#160;</h3><h1 align='center'>World Quest Tab</h1><h3>&#160;</h3><h1 align='center'>11.0.5</h1><p>Update for 11.0.5</p><h3>&#160;</h3><h3>&#160;</h3><h2>Fixes:</h2><p>Fixed alot of lua errors.</p><h3>&#160;</h3><h3>&#160;</h3><h1 align='center'>11.0.2.13</h1><h2>Fixes:</h2><p>World quests of City of Threads on Azj-Kahet now displays correctly.</p><h3>&#160;</h3><p>Bonus world quests are now fully working.</p><h3>&#160;</h3><h3>&#160;</h3><h1 align='center'>11.0.2.12</h1><h2>Fixes:</h2><p>Current world quest was not showing on map.</p><h3>&#160;</h3><h3>&#160;</h3><h1 align='center'>11.0.2.11</h1><h2>Fixes:</h2><p>Now World Map filters work correctly and updates WorldQuestTab filters. Should fix some quests that were displayed as world quests.</p><h3>&#160;</h3><p>Pet battles filter now working as intended.</p><h3>&#160;</h3><p>Added missing Skyriding filter option.</p><h3>&#160;</h3><h3>&#160;</h3><h1 align='center'>11.0.2.10</h1><h2>Changes:</h2><p>Disabled WorldQuestTabUti WQT_DEFAULTS = <table> {
 }
 WQT_TYPEFLAG_LABELS = <table> {
 }
 WQT_COLOR_WEAPON = <table> {
 }
 ENUM_PIN_ZONE = <table> {
 }
 SETTING_CATEGORIES = <table> {
 }
 WQT_CONTINENT_GROUPS = <table> {
 }
 WQT_TYPE_BONUSOBJECTIVE = 99
 WQT_SORT_OPTIONS = <table> {
 }
 WQT_ZONE_MAPCOORDS = <table> {
 }
 FILTER_TYPES = <table> {
 }
 SORT_OPTION_ORDER = <table> {
 }
 COLOR_IDS = <table> {
 }
 WQT_GREEN_FONT_COLOR = <table> {
 }
 WQT_BOUNTYBOARD_OVERLAYID = 5
 WQT_NO_FACTION_DATA = <table> {
 }
 WQT_COLOR_ITEM = <table> {
 }
 FILTER_FUNCTIONS = <table> {
 }
 ENUM_PIN_CONTINENT = <table> {
 }
 WQT_ORANGE_FONT_COLOR = <table> {
 }
 SORT_FUNCTIONS = <table> {
 }
 ZONE_SUBZONES = <table> {
 }
 FILTER_TYPE_OLD_CONTENT = <table> {
 }
 RING_TYPES = <table> {
 }
 WQT_FACTION_DATA = <table> {
 }
 PIN_CENTER_TYPES = <table> {
 }
 TOOLTIP_STYLES = <table> {
 }
 WQT_CVAR_LIST = <table> {
 }
 WQT_LISTITTEM_HEIGHT = 32
 WQT_COLOR_HONOR = <table> {
 }
 WARMODE_BONUS_REWARD_TYPES = <table> {
 }
 TIME_REMAINING_CATEGORY = <table> {
 }
 WQT_COLOR_CURRENCY = <table> {
 }
 WQT_COLOR_RELIC = <table> {
 }
 SETTING_LIST = <table> {
 }
 SETTING_TYPES = <table> {
 }
 RING_TYPES_LABELS = <table> {
 }
 WQT_BLUE_FONT_COLOR = <table> {
 }
 CONDUIT_SUBTYPE = <table> {
 }
 PIN_CENTER_LABELS = <table> {
 }
 NUMBER_ABBREVIATIONS_ASIAN = <table> {
 }
 PATH_CUSTOM_ICONS = "Addons/WorldQuestTab/Images/CustomIcons"
 QUESTS_NOT_COUNTING = <table> {
 }
 WQT_COLOR_ARMOR = <table> {
 }
 WQT_COLOR_MISSING = <table> {
 }
 WQT_COLOR_GOLD = <table> {
 }
 LIST_ANCHOR_TYPE = <table> {
 }
 WQT_COLOR_NONE = <table> {
 }
 WQT_WHITE_FONT_COLOR = <table> {
 }
}
_emptyTable = <table> {
}
WQT = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 filterOrders = <table> {
 }
 name = "WorldQuestTab"
 orderedModules = <table> {
 }
 isEnabled = true
 baseName = "WorldQuestTab"
 mapWQProvider = <table> {
 }
 defaultModuleState = true
 loadableExternals = <table> {
 }
 settings = <table> {
 }
 db = <table> {
 }
 enabledState = true
}

**Comment by NanMetal** [comment]
Please do a clean install of the addon, delete your profile file "WorldQuestTab.lua" inside WTF/YourAccount/SavedVariables or search "WorldQuestTab.lua" in the WTF folder and try again

**Comment by FaithfulDev** [comment]
@reyard Did that help you? 

Just a side note: When posting technical errors, which may contain special formatting characters or strings, it's best to put it in a code block. This will suppress any formatting and show your paste as is.

![image](https://github.com/user-attachments/assets/3773ce11-fafa-487c-a8c9-edf9065a81be)
